# Generated by Django 5.0.6 on 2024-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(max_length=8, unique=True)),
                ('items', models.ManyToManyField(to='einkaufsliste.shoppingitem')),
            ],
        ),
    ]
