# Generated by Django 5.0.6 on 2024-10-05 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste', '0003_alter_shoppinglist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='items',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
