# Generated by Django 5.0.6 on 2024-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste', '0008_shoppingitem_added_on_shoppingitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
