# Generated by Django 5.0.6 on 2024-10-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste', '0009_shoppinglist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
