# Generated by Django 5.0.6 on 2024-10-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste', '0010_shoppingitem_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='name',
        ),
    ]
